apiVersion: v1
kind: Service
metadata:
  name: yuval-interview-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: yuval-interview
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
